/*
 * Global constants.
 * 
 * @date 28/02/2021
 * @author corentin romilly
 */
public with sharing class CORE_Constants {

    public static final String GEONAMESAPI_BASE               = 'http://api.geonames.org';
    public static final String GEONAMESAPI_ROUTE_WEATHERFINDNEAR = '/findNearByWeatherJSON';
    public static final String GEONAMESAPI_ROUTE_GEOCODEADDRESS  = '/geoCodeAddressJSON';
    public static final String GEONAMESAPI_USERNAME              = 'illymor';

    // here come global others constants
}